### ISSUE TITLE
Add workflow for merged pull requests

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#223]
[PR merge workflow from GitHub Docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges):

```yml
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
```

We don't know what happens here. Is there a checkout, and what is it checking out (main/master)?

Test on your own repo first to figure out what variables are set. Will radia_run ci-pull-request work out of the box?
