### ISSUE TITLE
20240131 Update readthedocs generation

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/pykern#386]
Precipitated by [this notification](https://blog.readthedocs.com/drop-support-system-packages/). Investigate how they currently generate this documentation vs the new method and make changes accordingly.

See also radiasoft/pykern#37

- [x] radiasoft/pykern#429
- [x] radiasoft/pykern#393
- [x] https://github.com/radiasoft/download/issues/526
- [ ] radiasoft/devsecops#521

To clarify a bit, here's what readthedocs is expecting in the repo of interest:
- .readthedocs.yml at the root level, minimally:
```yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
     - <commands to run>

sphinx:
  configuration: docs/conf.py

python:
    install:
    - requirements: docs/requirements.txt
```
- docs/conf.py
- docs/requirements.txt

In the current state of PR radiasoft/pykern#392, "commands to run" is `python setup.py install --force` (which readthedocs used to do automatically). That's done to run pksetup, which generates the conf.py above; accordingly, requirements.txt contains pykern. The purpose of radiasoft/pykern#393 is to take pksetup out of the process and the purpose of https://github.com/radiasoft/download/issues/526 is to make "commands to run" something like `curl https://radia.run | bash -s readthedocs`
