### ISSUE TITLE
Multiple top-level packages discovered in a flat-layout: ['run', 'pykern'].

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#514]
Sirepo has:

```toml
[tool.setuptools.packages.find]
include = ["sirepo*"]
```

This seemed to work, and might be more reliable:

```toml
[tool.setuptools]
packages = ["pykern"]
```
